FROM node:20-slim AS base

WORKDIR /usr/src/app

COPY frontend/package.json frontend/package-lock.json* ./frontend/
WORKDIR /usr/src/app/frontend
RUN npm install

COPY frontend .

RUN npm run build

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
